import {useEffect,useRef,useState} from "react";
import {useOwnerSession} from "./OwnerSession";
import "./admin-accounts.css";
type Account={id:string;username:string;email:string;role:"admin"|"user";disabled:boolean;must_change_password:boolean};
type Capacity={available_bytes:number;admission_remaining_bytes:number;warning:boolean;accounts:{account_id:string;quota_bytes:number;logical_bytes:number;state:string;pending_quota?:boolean}[]};
async function request<T>(path:string,method="GET",body?:unknown):Promise<T>{const response=await fetch(path,{method,credentials:"same-origin",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(value.error?.message??"操作失败，请重试");return value as T}
export function AdminAccounts(){
 const session=useOwnerSession();const [accounts,setAccounts]=useState<Account[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const busyRef=useRef(false);const [reset,setReset]=useState<string|null>(null);const [capacity,setCapacity]=useState<Capacity|null>(null);const [capacityError,setCapacityError]=useState("");
 const allowed=session?.multi_account&&session.owner?.role==="admin";
 const refresh=async()=>{setAccounts(await request<Account[]>("/api/admin/accounts"));try{setCapacity(await request<Capacity>("/api/admin/capacity"));setCapacityError("")}catch{setCapacity(null);setCapacityError("电脑容量暂不可用，请刷新后重试")}};
 useEffect(()=>{if(allowed)void refresh().catch(e=>setError(String(e.message)))},[allowed]);
 async function action(work:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");try{await work();await refresh()}catch(e){setError(e instanceof Error?e.message:"操作失败");try{await refresh()}catch{}}finally{busyRef.current=false;setBusy(false)}}
 if(!allowed)return null;
 return <section className="admin-accounts" aria-busy={busy}>
  <p className="admin-intro">仅 Admin 可以预创建账号。用户首次登录必须更换初始密码；停用保留工作区，并撤销登录状态。</p>
  {capacityError&&<p role="status" className="admin-intro">{capacityError}</p>}
  {capacity&&<p className="admin-intro">可分配电脑容量 {Math.max(0,capacity.admission_remaining_bytes/2**30).toFixed(1)} GiB{capacity.warning?" · 剩余空间不足，请谨慎分配":""}。扩容会停止电脑，完成后可重新连接；缩盘需要单独离线处理，停用不会释放容量。</p>}
  <form className="admin-create" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(!String(data.get("username")??"").trim()&&!String(data.get("email")??"").trim()){setError("请填写用户名或邮箱");return}void action(async()=>{await request("/api/admin/accounts","POST",{username:data.get("username"),email:data.get("email"),password:data.get("password")});form.reset()})}}>
   <h3>添加账号</h3><label>用户名<input name="username" autoComplete="off" maxLength={64} disabled={busy}/></label><label>邮箱<input name="email" type="email" autoComplete="off" maxLength={254} disabled={busy}/></label><label>初始密码<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={1024} required disabled={busy}/></label><button type="submit" className="primary-button" disabled={busy}>创建账号</button>
  </form>
  {error&&<p role="alert" className="admin-error">{error}</p>}
  <div className="admin-account-list">{accounts.map(account=>{const disk=capacity?.accounts.find(disk=>disk.account_id===account.id);return <article key={account.id} className="admin-account-row"><div><strong>{account.username}</strong><small>{account.email.endsWith("@account.invalid")?"未设置邮箱":account.email}</small><span>{account.role==="admin"?"Admin":"普通用户"} · {account.disabled?"已停用":account.must_change_password?"等待更换初始密码":"正常"}</span></div><div className="admin-account-actions"><button disabled={busy||account.id===session.owner?.id} onClick={()=>void action(async()=>{await request(`/api/admin/accounts/${account.id}`,"PATCH",{disabled:!account.disabled})})}>{account.disabled?"恢复账号":"停用账号"}</button><button disabled={busy||account.id===session.owner?.id} onClick={()=>void action(async()=>{await request(`/api/admin/accounts/${account.id}`,"PATCH",{role:account.role==="admin"?"user":"admin"})})}>{account.role==="admin"?"设为普通用户":"设为 Admin"}</button><button disabled={busy} onClick={()=>setReset(reset===account.id?null:account.id)}>重设初始密码</button></div>{disk&&<form className="admin-quota" onSubmit={event=>{event.preventDefault();const quota=Number(new FormData(event.currentTarget).get("quota"));void action(async()=>{await request(`/api/admin/accounts/${account.id}/quota`,"PATCH",{quota_gib:quota})})}}>{disk.pending_quota&&<p role="status" className="admin-intro">扩容尚未完成，预留容量已保留；请在电脑清理完成后重试此配额。</p>}<label>电脑容量（GiB）<input key={disk.quota_bytes} name="quota" type="number" min={Math.max(8,(disk.quota_bytes??0)/2**30)} max={1024} step={1} defaultValue={disk.quota_bytes/2**30} required disabled={busy}/></label><button disabled={busy}>保存容量并停止电脑</button></form>}{reset===account.id&&<form className="admin-reset" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const password=new FormData(form).get("password");void action(async()=>{await request(`/api/admin/accounts/${account.id}`,"PATCH",{initial_password:password});form.reset();setReset(null)})}}><label>新初始密码<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={1024} disabled={busy}/></label><button disabled={busy}>更新并撤销登录</button><button type="button" disabled={busy} onClick={()=>setReset(null)}>取消</button></form>}</article>})}</div>
 </section>
}
