import {useEffect,useRef,useState} from "react";
import {useOwnerSession} from "./OwnerSession";
import "./admin-accounts.css";
import {i18n,useTranslation} from "./i18n";
type Account={id:string;username:string;email:string;role:"admin"|"user";disabled:boolean;must_change_password:boolean};
type Capacity={available_bytes:number;admission_remaining_bytes:number;warning:boolean;accounts:{account_id:string;quota_bytes:number;logical_bytes:number;state:string;pending_quota?:boolean}[]};
async function request<T>(path:string,method="GET",body?:unknown):Promise<T>{const response=await fetch(path,{method,credentials:"same-origin",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(value.error?.message??i18n.t("settings:action.failed"));return value as T}
export function AdminAccounts(){
 const {t}=useTranslation("settings");
 const session=useOwnerSession();const [accounts,setAccounts]=useState<Account[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const busyRef=useRef(false);const [reset,setReset]=useState<string|null>(null);const [capacity,setCapacity]=useState<Capacity|null>(null);const [capacityError,setCapacityError]=useState("");
 const allowed=session?.multi_account&&session.owner?.role==="admin";
 const refresh=async()=>{setAccounts(await request<Account[]>("/api/admin/accounts"));try{setCapacity(await request<Capacity>("/api/admin/capacity"));setCapacityError("")}catch{setCapacity(null);setCapacityError(t("admin.capacity_unavailable"))}};
 useEffect(()=>{if(allowed)void refresh().catch(e=>setError(String(e.message)))},[allowed]);
 async function action(work:()=>Promise<void>){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");try{await work();await refresh()}catch(e){setError(e instanceof Error?e.message:t("action.failed"));try{await refresh()}catch{}}finally{busyRef.current=false;setBusy(false)}}
 if(!allowed)return null;
 return <section className="admin-accounts" aria-busy={busy}>
  <p className="admin-intro">{t("admin.intro")}</p>
  {capacityError&&<p role="status" className="admin-intro">{capacityError}</p>}
  {capacity&&<p className="admin-intro">{t(capacity.warning?"admin.capacity_low":"admin.capacity",{size:Math.max(0,capacity.admission_remaining_bytes/2**30).toFixed(1)})}</p>}
  <form className="admin-create" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);if(!String(data.get("username")??"").trim()&&!String(data.get("email")??"").trim()){setError(t("admin.name_required"));return}void action(async()=>{await request("/api/admin/accounts","POST",{username:data.get("username"),email:data.get("email"),password:data.get("password")});form.reset()})}}>
   <h3>{t("admin.add_title")}</h3><label>{t("admin.username")}<input name="username" autoComplete="off" maxLength={64} disabled={busy}/></label><label>{t("admin.email")}<input name="email" type="email" autoComplete="off" maxLength={254} disabled={busy}/></label><label>{t("admin.initial_password")}<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={1024} required disabled={busy}/></label><button type="submit" className="primary-button" disabled={busy}>{t("admin.create")}</button>
  </form>
  {error&&<p role="alert" className="admin-error">{error}</p>}
  <div className="admin-account-list">{accounts.map(account=>{const disk=capacity?.accounts.find(disk=>disk.account_id===account.id);return <article key={account.id} className="admin-account-row"><div><strong>{account.username}</strong><small>{account.email.endsWith("@account.invalid")?t("admin.no_email"):account.email}</small><span>{account.role==="admin"?t("admin.role_admin"):t("admin.role_user")} · {account.disabled?t("admin.state_disabled"):account.must_change_password?t("admin.state_must_change"):t("admin.state_active")}</span></div><div className="admin-account-actions"><button disabled={busy||account.id===session.owner?.id} onClick={()=>void action(async()=>{await request(`/api/admin/accounts/${account.id}`,"PATCH",{disabled:!account.disabled})})}>{account.disabled?t("admin.enable"):t("admin.disable")}</button><button disabled={busy||account.id===session.owner?.id} onClick={()=>void action(async()=>{await request(`/api/admin/accounts/${account.id}`,"PATCH",{role:account.role==="admin"?"user":"admin"})})}>{account.role==="admin"?t("admin.make_user"):t("admin.make_admin")}</button><button disabled={busy} onClick={()=>setReset(reset===account.id?null:account.id)}>{t("admin.reset_password")}</button></div>{disk&&<form className="admin-quota" onSubmit={event=>{event.preventDefault();const quota=Number(new FormData(event.currentTarget).get("quota"));void action(async()=>{await request(`/api/admin/accounts/${account.id}/quota`,"PATCH",{quota_gib:quota})})}}>{disk.pending_quota&&<p role="status" className="admin-intro">{t("admin.quota_pending")}</p>}<label>{t("admin.quota_label")}<input key={disk.quota_bytes} name="quota" type="number" min={Math.max(8,(disk.quota_bytes??0)/2**30)} max={1024} step={1} defaultValue={disk.quota_bytes/2**30} required disabled={busy}/></label><button disabled={busy}>{t("admin.quota_save")}</button></form>}{reset===account.id&&<form className="admin-reset" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const password=new FormData(form).get("password");void action(async()=>{await request(`/api/admin/accounts/${account.id}`,"PATCH",{initial_password:password});form.reset();setReset(null)})}}><label>{t("admin.new_password")}<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={1024} disabled={busy}/></label><button disabled={busy}>{t("admin.reset_submit")}</button><button type="button" disabled={busy} onClick={()=>setReset(null)}>{t("action.cancel")}</button></form>}</article>})}</div>
 </section>
}
