package executor

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync/atomic"
	"time"
)

// GvisorExecutor runs commands inside gVisor sandboxes via `runsc run`.
// Each sandbox is one OCI bundle written to ~/.tofi/runs/{runID}/ with a
// config.json generated by BuildOCIConfig. The bundle is destroyed after the
// command returns.
type GvisorExecutor struct {
	homeDir  string // ~/.tofi
	runscBin string // path to the runsc binary
	uid      uint32 // uid the sandboxed process runs as
	gid      uint32
	stateDir string // runsc --root state directory
}

var gvisorContainerSeq uint64

// NewGvisorExecutor builds an executor. runscBin must be an absolute path.
// Uses the current OS user's uid/gid for in-sandbox identity so that files
// created in bind-mounted user dirs stay owned by the real user.
func NewGvisorExecutor(homeDir, runscBin string) (*GvisorExecutor, error) {
	if homeDir == "" {
		return nil, fmt.Errorf("homeDir is required")
	}
	if runscBin == "" {
		return nil, fmt.Errorf("runscBin is required")
	}

	stateDir := filepath.Join(homeDir, "runsc-state")
	if err := os.MkdirAll(stateDir, 0700); err != nil {
		return nil, fmt.Errorf("create runsc state dir: %w", err)
	}
	// In --rootless mode, runsc maps host uid → sandbox uid 0. The OCI spec's
	// process uid must therefore be 0, not the host uid, or the sandbox
	// process will run under an unmapped uid with no filesystem access.
	return &GvisorExecutor{
		homeDir:  homeDir,
		runscBin: runscBin,
		uid:      0,
		gid:      0,
		stateDir: stateDir,
	}, nil
}

// CreateSandbox materialises the dir tree this run needs on the host.
// sandboxPath returned = ~/.tofi/runs/{CardID}.
func (g *GvisorExecutor) CreateSandbox(cfg SandboxConfig) (string, error) {
	if cfg.CardID == "" {
		return "", fmt.Errorf("CardID is required")
	}
	homeDir := cfg.HomeDir
	if homeDir == "" {
		homeDir = g.homeDir
	}

	pkgDir := filepath.Join(homeDir, "packages")
	for _, sub := range []string{
		"cache/pip", "cache/uv", "cache/npm",
		"wheels", "artifacts",
	} {
		if err := os.MkdirAll(filepath.Join(pkgDir, sub), 0755); err != nil {
			return "", fmt.Errorf("create packages dir %s: %w", sub, err)
		}
	}

	if cfg.UserID != "" {
		userRoot := filepath.Join(homeDir, "users", cfg.UserID)
		if err := ensurePersistentUserDirs(userRoot); err != nil {
			return "", fmt.Errorf("create user dir: %w", err)
		}
		if err := ensureUserVenv(userRoot); err != nil {
			return "", fmt.Errorf("create user venv: %w", err)
		}
	}

	runDir := filepath.Join(homeDir, "runs", cfg.CardID)
	for _, sub := range []string{"tmp", "overlay/local", "rootfs"} {
		if err := os.MkdirAll(filepath.Join(runDir, sub), 0755); err != nil {
			return "", fmt.Errorf("create run dir %s: %w", sub, err)
		}
	}
	if err := ensurePersistentUserDirs(filepath.Join(runDir, "overlay", "local")); err != nil {
		return "", fmt.Errorf("prepare ephemeral overlay: %w", err)
	}
	return runDir, nil
}

// Execute writes the OCI config.json, runs the sandbox via `runsc run`, and
// returns combined stdout/stderr. Install mode is picked from env
// TOFI_INSTALL_MODE (default persistent).
func (g *GvisorExecutor) Execute(ctx context.Context, sandboxPath, userDir, command string, timeoutSec int, env map[string]string) (string, error) {
	if sandboxPath == "" {
		return "", fmt.Errorf("sandboxPath is required")
	}
	if timeoutSec <= 0 {
		timeoutSec = 60
	}
	if timeoutSec > MaxTimeout {
		timeoutSec = MaxTimeout
	}

	homeDir := g.homeDir
	if homeDir == "" {
		homeDir = filepath.Dir(filepath.Dir(sandboxPath))
	}
	pkgDir := filepath.Join(homeDir, "packages")

	mode := InstallModePersistent
	if env["TOFI_INSTALL_MODE"] == string(InstallModeEphemeral) {
		mode = InstallModeEphemeral
	}

	if mode == InstallModePersistent && userDir == "" {
		return "", fmt.Errorf("persistent install mode requires userDir")
	}

	// In ephemeral mode /home/tofi/.local is bind-mounted to
	// {sandboxPath}/overlay/local, a per-run scratch dir. Lazily materialise
	// a venv there so pip installs inside the sandbox don't fail with
	// "Could not find an activated virtualenv".
	if mode == InstallModeEphemeral {
		if err := ensureUserVenv(filepath.Join(sandboxPath, "overlay", "local")); err != nil {
			return "", fmt.Errorf("create ephemeral venv: %w", err)
		}
	}

	extraEnv := make([]string, 0, len(env))
	for k, v := range env {
		if k == "TOFI_INSTALL_MODE" {
			continue
		}
		extraEnv = append(extraEnv, k+"="+v)
	}

	spec, err := BuildOCIConfig(OCISpecOptions{
		Command:     command,
		UID:         g.uid,
		GID:         g.gid,
		RunDir:      sandboxPath,
		UserDir:     userDir,
		PkgDir:      pkgDir,
		InstallMode: mode,
		TimeoutSec:  timeoutSec,
		ExtraEnv:    extraEnv,
	})
	if err != nil {
		return "", fmt.Errorf("build OCI spec: %w", err)
	}
	containerID := newContainerID(filepath.Base(sandboxPath))
	bundleDir := filepath.Join(sandboxPath, ".runsc-bundles", containerID)
	if err := os.MkdirAll(bundleDir, 0755); err != nil {
		return "", fmt.Errorf("create runsc bundle dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(bundleDir, "rootfs"), 0755); err != nil {
		return "", fmt.Errorf("create runsc bundle rootfs: %w", err)
	}
	defer os.RemoveAll(bundleDir)

	configPath := filepath.Join(bundleDir, "config.json")
	if err := os.WriteFile(configPath, spec, 0644); err != nil {
		return "", fmt.Errorf("write config.json: %w", err)
	}

	logAuditLine(sandboxPath, command)

	runCtx, cancel := context.WithTimeout(ctx, time.Duration(timeoutSec)*time.Second)
	defer cancel()

	// Flags required to run runsc as a non-root user under systemctl --user:
	//   --rootless       single-user namespace: sandboxed process appears as
	//                    root inside but stays mapped to the host UID
	//                    outside. Skips newuidmap/newgidmap (our
	//                    subuid/subgid ranges aren't wired for multi-UID
	//                    containers).
	//   --ignore-cgroups runsc otherwise tries to create a sub-cgroup per
	//                    sandbox and hits EPERM on cgroup.subtree_control
	//                    without explicit delegation. Per-process rlimits
	//                    (NPROC/NOFILE/FSIZE/CPU) in the OCI spec stay in
	//                    effect — enough to bound one sandbox.
	//   --network=host   --rootless is incompatible with gVisor's own
	//                    netstack. Host network means no egress isolation;
	//                    that's acceptable for now and will be replaced by
	//                    a host-side iptables allowlist in a later branch.
	//                    We still keep mount, pid, ipc, uts, and mount-ns
	//                    isolation — the primary wins over DevExecutor.
	cmd := exec.CommandContext(runCtx,
		g.runscBin,
		"--root", g.stateDir,
		"--network=host",
		"--rootless",
		"--ignore-cgroups",
		"run",
		"--bundle", bundleDir,
		containerID,
	)
	defer g.forceDelete(containerID)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &limitedWriter{w: &stdout, limit: MaxOutputBytes}
	cmd.Stderr = &limitedWriter{w: &stderr, limit: MaxOutputBytes}

	log.Printf("🛡️  [gvisor] runsc run %s (%.80s…)", containerID, command)
	runErr := cmd.Run()

	output := stdout.String()
	if errOut := stderr.String(); errOut != "" {
		if output != "" {
			output += "\n"
		}
		output += errOut
	}

	if runCtx.Err() == context.DeadlineExceeded {
		g.forceDelete(containerID)
		return output, fmt.Errorf("command timed out after %d seconds", timeoutSec)
	}
	if runErr != nil {
		return output, fmt.Errorf("command failed: %v\n%s", runErr, output)
	}
	return strings.TrimRight(output, "\n"), nil
}

// Cleanup removes the run directory and any leftover runsc state.
func (g *GvisorExecutor) Cleanup(sandboxPath string) {
	if sandboxPath == "" {
		return
	}
	if !strings.Contains(sandboxPath, "/runs/") {
		return
	}
	containerID := filepath.Base(sandboxPath)
	g.forceDelete(containerID)
	_ = os.RemoveAll(sandboxPath)
}

func (g *GvisorExecutor) forceDelete(containerID string) {
	cmd := exec.Command(g.runscBin, "--root", g.stateDir, "delete", "--force", containerID)
	_ = cmd.Run()
}

func newContainerID(prefix string) string {
	prefix = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' || r == '.' {
			return r
		}
		return '-'
	}, prefix)
	if prefix == "" {
		prefix = "tofi"
	}
	seq := atomic.AddUint64(&gvisorContainerSeq, 1)
	return fmt.Sprintf("%s-%d-%d", prefix, time.Now().UnixNano(), seq)
}

// ensureUserVenv lazily materialises the user's default Python venv on the
// host so the sandbox sees a working virtualenv when bind-mounted.
// Idempotent: skips if venv already exists. The in-sandbox path
// /home/tofi/.local/python/venvs/default is bind-mapped to
// {userRoot}/python/venvs/default, so what we create on host is what the
// sandbox sees.
func ensureUserVenv(userRoot string) error {
	venvPath := filepath.Join(userRoot, "python", "venvs", "default")
	if _, err := os.Stat(filepath.Join(venvPath, "bin", "python")); err == nil {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(venvPath), 0755); err != nil {
		return err
	}
	cmd := exec.Command("python3", "-m", "venv", "--system-site-packages", venvPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("python3 -m venv %s: %v\n%s", venvPath, err, out)
	}
	return nil
}

// ensurePersistentUserDirs creates the full user/{uid} subtree expected by
// the OCI spec and the runtime shims.
func ensurePersistentUserDirs(root string) error {
	for _, sub := range []string{
		"bin",
		"config",
		"cache",
		"state/tool-runs",
		"python/venvs",
		"npm",
		"uv/tools",
		"artifacts",
	} {
		if err := os.MkdirAll(filepath.Join(root, sub), 0755); err != nil {
			return err
		}
	}
	return nil
}

// logAuditLine appends a timestamped record to sandboxPath/audit.log.
// Kept inside the ephemeral run dir — it is not a security audit log,
// just a debugging trail that disappears on teardown.
func logAuditLine(sandboxPath, command string) {
	f, err := os.OpenFile(filepath.Join(sandboxPath, "audit.log"),
		os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return
	}
	defer f.Close()
	fmt.Fprintf(f, "[%s] %s\n", time.Now().Format(time.RFC3339), command)
}
